security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_CLIENT
        ROLE_FREELANCER:  ROLE_DESIGNER
        ROLE_ADMIN:       ROLE_IMPRIMEUR&&
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)
            security: false
        main:
            anonymous: ~
            pattern: ^/
            form_login:
                #default_target_path: /nomDeLaRouteDefinieDansLeRouteur
                provider: fos_userbundle
                #csrf_provider: form.csrf_provider
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
            logout:
                path:     fos_user_security_logout
                target:   fos_user_security_login
            remember_me:
                secret:   %secret%
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/client, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
